### ISSUE TITLE
Error can't backup database or files

### ISSUE THREAD

**Issue by Balindil** [menatwork/syncCto#267] opened 2016-05-06 12:07 UTC
Conto 3.5.12, synccto 3.2.0-beta8, PHP-Version 5.6.19

If I try to backup database:

``` php
Fatal error: Call to undefined method SyncCtoHelper::getReadableSize() in /www/htdocs/.../composer/vendor/menatwork/synccto/system/modules/syncCto/SyncCtoHelper.php on line 1142
```

Backup files:

``` php
Fatal error: Call to a member function parse() on null in /www/htdocs/.../system/modules/generalDriver/templates/dcbe_general_field.html5 on line 3
```

**Comment by Saschlong** [comment] 2016-05-19 12:09
Same problem with Contao 3.5.6. But in my case the File Backup works.

**Comment by fritzmg** [comment] 2016-05-20 09:12
Same error here as well. Any ETA on the fix?

**Comment by stefanheimes** [comment] 2016-05-31 14:37
Today ;)

**Comment by stefanheimes** [comment] 2016-05-31 14:49
The first bug is fixed with the hotfix. 

The second bug is not a bug.... 
```/www/htdocs/.../system/modules/generalDriver/templates/dcbe_general_field.html5``` is not the right template of the DCG. 

I think you have both versions from the DCG the old one from MetaModels and the new one from the CCA. Please take a look if you have the folders ```dc-general``` and ```generalDriver``` under ```system/modules```. If you have both, remove the ```generalDriver``` folder (Make a backup from the folder ;)). This should fix the problem.

**Comment by stefanheimes** [comment] 2016-05-31 15:11
New version is tagged.

**Comment by fritzmg** [comment] 2016-06-03 14:17
Database backup works in beta9 :)

**Closed** 2016-11-18 16:44 UTC
Labels: Defect, Testing
